# collect-usecases.ps1
# ------------------------------
# Setup paths
# ------------------------------

# Project root = parent of Scripts
$root = Split-Path -Parent $PSScriptRoot

# Output folder inside Use-Cases
$outputFolder = Join-Path $root "Use-Cases\Generated-UseCases-JSON"

# Ensure folder exists
if (-not (Test-Path $outputFolder)) {
    New-Item -Path $outputFolder -ItemType Directory | Out-Null
}

# Output files
$outputRaw   = Join-Path $outputFolder "All-UseCases.json"
$outputFixed = Join-Path $outputFolder "All-UseCases-Fixed.json"
$readme      = Join-Path $outputFolder "README.md"

# Create output folder if it doesn't exist
if (-not (Test-Path $outputFolder)) {
    New-Item -Path $outputFolder -ItemType Directory | Out-Null
}

# ------------------------------
# STEP 1: Collect raw blocks
# ------------------------------

# Clear old output
"" | Out-File $outputRaw -Encoding UTF8

# Collect all UC-* folders with .html files
$files = Get-ChildItem -Path $root -Recurse -Filter "*.html" | Where-Object { $_.Directory.Name -like "UC-*" }

# Sort files by UC number
$files = $files | Sort-Object { 
    if ($_ -match "UC-(\d+)") { [int]$matches[1] } else { 9999 } 
}

# Start JSON array
"[" | Out-File $outputRaw -Encoding UTF8 -Append

$first = $true
foreach ($file in $files) {
    $lines = Get-Content $file.FullName

    # Get first occurrence of start
    $startMatch = $lines | Select-String -Pattern "const useCaseData = {" | Select-Object -First 1
    if ($startMatch) {
        $start = $startMatch.LineNumber

        # Find first closing "};" after that
        $endMatch = $lines[$start..($lines.Length-1)] | Select-String -Pattern "};" | Select-Object -First 1
        if ($endMatch) {
            $end = $endMatch.LineNumber + $start - 1

            # Extract block safely
            $block = $lines[($start-1)..($end)]

            if (-not $first) {
                "," | Out-File $outputRaw -Encoding UTF8 -Append
            }

            $block -replace "^const useCaseData\s*=\s*", "" -replace ";\s*$","" | Out-File $outputRaw -Encoding UTF8 -Append
            $first = $false
        }
    }
}

# End JSON array
"]" | Out-File $outputRaw -Encoding UTF8 -Append
Write-Host "✅ Raw use cases collected in sorted order into $outputRaw"

# ------------------------------
# STEP 2: Fix JSON keys
# ------------------------------

# Regex: match a key followed by colon
$regex = '^\s*([A-Za-z0-9\-\s\(\)]+):'

Get-Content $outputRaw | ForEach-Object {
    $line = $_
    if ($line -match $regex) {
        $key = $matches[1].Trim()
        $line = $line -replace $regex, ('"' + $key + '":')
    }
    $line
} | Out-File $outputFixed -Encoding UTF8

Write-Host "✅ Fixed JSON saved as $outputFixed"

# ------------------------------
# STEP 3: Generate README.md
# ------------------------------

$scriptRelativePath = "Scripts/collect-and-fix-usecases.ps1"
$readmeContent = @"
# Generated Use-Cases JSON

This folder contains JSON files automatically generated from all Use-Case HTML files in the project.

## Files

- **All-UseCases.json**: Raw JSON extracted from all Use-Case HTML files, sorted by UC number.
- **All-UseCases-Fixed.json**: JSON with properly quoted keys for valid syntax.

## Generated By

These files were generated by the script located at:

\`$scriptRelativePath\`

> ⚠️ Do not edit these JSON files manually. Any changes should be made in the original Use-Case HTML files.

## Notes

- All UC-* HTML files under the project have been scanned recursively.
- The output folder is: `$outputFolder`
"@

$readmeContent | Out-File $readme -Encoding UTF8
Write-Host "✅ README.md created at $readme"
